'use client';
import './login.css';
import { useEffect, useState } from 'react';

type Metric = { owners:number; pets:number; upcomingAppointments:number; overdueVaccinations:number };
type Pet = { id:string; name:string; species:string; petTag:string; owner:{ fullName:string }; vaccinations:{ vaccineName:string; nextDueDate:string; status:string }[] };
type Vaccination = { id:string; vaccineName:string; nextDueDate:string; status:string; pet:{ name:string } };
const api = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/api/v1';

export default function Home() {
  const [token, setToken] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  const [metrics, setMetrics] = useState<Metric | null>(null); const [pets, setPets] = useState<Pet[]>([]); const [vaccinations, setVaccinations] = useState<Vaccination[]>([]); const [search, setSearch] = useState('');
  async function login(event: React.FormEvent) { event.preventDefault(); setError(''); const response = await fetch(`${api}/auth/login`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ email, password }) }); const body = await response.json(); if (!body.success) { setError(body.error?.message ?? 'No se pudo iniciar sesion'); return; } setToken(body.data.token); localStorage.setItem('happy-paws-token', body.data.token); }
  useEffect(() => { const stored = localStorage.getItem('happy-paws-token'); if (stored) setToken(stored); }, []);
  useEffect(() => { if (!token) return; const headers = { Authorization:`Bearer ${token}` }; Promise.all([fetch(`${api}/dashboard`, { headers }), fetch(`${api}/pets`, { headers }), fetch(`${api}/vaccinations`, { headers })]).then(async ([a,b,c]) => { const [dashboard, petList, vaccineList] = await Promise.all([a.json(),b.json(),c.json()]); setMetrics(dashboard.data); setPets(petList.data ?? []); setVaccinations(vaccineList.data ?? []); }).catch(() => setError('No se pudo conectar con la API.')); }, [token]);
  useEffect(() => { if (!token) return; const timeout = setTimeout(() => fetch(`${api}/pets?search=${encodeURIComponent(search)}`, { headers:{Authorization:`Bearer ${token}`} }).then(response => response.json()).then(body => setPets(body.data ?? [])), 250); return () => clearTimeout(timeout); }, [search, token]);
  if (!token) return <main className="login"><section><div className="eyebrow">Happy Paws Veterinary Clinic</div><h1>Care Central</h1><p>El pulso diario de una clínica que cuida de verdad.</p><form onSubmit={login}><label>Correo<input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="admin@happypaws.com" required /></label><label>Contraseña<input type="password" value={password} onChange={event => setPassword(event.target.value)} required /></label><button type="submit">Entrar al centro</button>{error && <small className="error">{error}</small>}</form></section></main>;
  return <div className="shell"><aside className="rail"><div className="brand">happy<br/><span>paws</span> central</div><nav className="nav"><button className="active">Resumen</button><button>Pacientes</button><button>Citas</button><button>Vacunas</button></nav></aside><main className="main"><header className="top"><div><div className="eyebrow">Vista general</div><h1>Buenos días, equipo.</h1></div><div className="date">Miércoles, 09 de septiembre</div></header><section className="metrics"><Metric label="Propietarios" value={metrics?.owners ?? 0}/><Metric label="Mascotas activas" value={metrics?.pets ?? 0}/><Metric label="Citas agendadas" value={metrics?.upcomingAppointments ?? 0}/><Metric label="Vacunas vencidas" value={metrics?.overdueVaccinations ?? 0} danger/></section><section className="grid"><div className="panel"><div className="panel-head"><h2>Pacientes recientes</h2><input className="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Nombre, teléfono o pet tag" /></div>{pets.length ? pets.map(pet => <div className="row" key={pet.id}><div><strong>{pet.name}</strong><small>{pet.species} · {pet.owner.fullName}</small></div><span className="tag">{pet.petTag}</span></div>) : <div className="empty">No hay pacientes para mostrar.</div>}</div><div className="panel"><div className="panel-head"><h2>Próximas vacunas</h2></div>{vaccinations.length ? vaccinations.slice(0,5).map(vaccine => <div className="row" key={vaccine.id}><div><strong>{vaccine.pet.name}</strong><small>{vaccine.vaccineName}</small></div><span className={`tag ${vaccine.status === 'OVERDUE' ? 'overdue' : ''}`}>{vaccine.status === 'OVERDUE' ? 'Vencida' : new Date(vaccine.nextDueDate).toLocaleDateString('es-CO')}</span></div>) : <div className="empty">Agenda despejada por ahora.</div>}</div></section></main></div>;
}
function Metric({ label, value, danger=false }: { label:string; value:number; danger?:boolean }) { return <article className="metric"><span className="mark" style={{ background: danger ? 'var(--coral)' : 'var(--teal)' }} /><strong>{value}</strong><p>{label}</p></article>; }
