create type public.vaccination_status as enum ('ADMINISTERED', 'PENDING', 'OVERDUE');

create table public.vaccinations (
  id bigint generated by default as identity primary key,
  pet_id bigint not null,
  appointment_id bigint,
  vaccine_name text not null,
  administered_at date not null,
  next_due_date date not null,
  status public.vaccination_status not null default 'PENDING',
  created_at timestamptz not null default now(),
  constraint vaccinations_dates_valid check (next_due_date >= administered_at)
);

create index vaccinations_next_due_date_idx on public.vaccinations (next_due_date);
create index vaccinations_pet_id_idx on public.vaccinations (pet_id);

alter table public.vaccinations enable row level security;

create policy "Owners can read their vaccinations"
  on public.vaccinations
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.pets
      join public.owners on owners.id = pets.owner_id
      where pets.id = vaccinations.pet_id
        and owners.auth_user_id = (select auth.uid())
    )
    or exists (
      select 1
      from public.profiles
      where profiles.id = (select auth.uid())
        and profiles.role in ('ADMIN', 'VET', 'RECEPTIONIST')
    )
  );

create policy "Veterinary staff can create vaccinations"
  on public.vaccinations
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.profiles
      where profiles.id = (select auth.uid())
        and profiles.role in ('ADMIN', 'VET')
    )
  );

create policy "Veterinary staff can update vaccinations"
  on public.vaccinations
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = (select auth.uid())
        and profiles.role in ('ADMIN', 'VET')
    )
  )
  with check (
    exists (
      select 1
      from public.profiles
      where profiles.id = (select auth.uid())
        and profiles.role in ('ADMIN', 'VET')
    )
  );