-- Happy Paws Care Central: esquema inicial de dominio.
-- Ejecutar en el SQL Editor del proyecto Supabase.

create extension if not exists pgcrypto;

do $$
begin
  create type public.user_role as enum ('ADMIN', 'VET', 'RECEPTIONIST', 'OWNER');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.appointment_status as enum ('SCHEDULED', 'COMPLETED', 'CANCELLED');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.vaccination_status as enum ('ADMINISTERED', 'PENDING', 'OVERDUE');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null,
  role public.user_role not null default 'OWNER',
  created_at timestamptz not null default now()
);

create table if not exists public.owners (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  full_name text not null,
  phone text not null,
  email text,
  address text,
  created_at timestamptz not null default now()
);

create table if not exists public.pets (
  id bigint generated by default as identity primary key,
  owner_id bigint not null references public.owners(id) on delete cascade,
  pet_tag text not null unique,
  name text not null,
  species text not null,
  breed text,
  birth_date date,
  weight numeric(5, 2) check (weight is null or weight > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  price_cents integer not null default 0 check (price_cents >= 0)
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  vet_id uuid references public.profiles(id) on delete set null,
  scheduled_at timestamptz not null,
  reason text not null,
  notes text,
  status public.appointment_status not null default 'SCHEDULED',
  created_at timestamptz not null default now()
);

create table if not exists public.appointment_services (
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  service_id bigint not null references public.services(id) on delete restrict,
  primary key (appointment_id, service_id)
);

create table if not exists public.vaccinations (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  appointment_id bigint references public.appointments(id) on delete set null,
  vaccine_name text not null,
  administered_at date not null,
  next_due_date date not null,
  status public.vaccination_status not null default 'PENDING',
  created_at timestamptz not null default now(),
  check (next_due_date >= administered_at)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_name text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists pets_owner_id_idx on public.pets(owner_id);
create index if not exists pets_name_idx on public.pets(lower(name));
create index if not exists pets_pet_tag_idx on public.pets(lower(pet_tag));
create index if not exists owners_phone_idx on public.owners(phone);
create index if not exists appointments_scheduled_at_idx on public.appointments(scheduled_at);
create index if not exists appointments_pet_id_idx on public.appointments(pet_id);
create index if not exists vaccinations_pet_id_idx on public.vaccinations(pet_id);
create index if not exists vaccinations_next_due_date_idx on public.vaccinations(next_due_date);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, 'Usuario'), '@', 1)),
    'OWNER'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.current_app_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

alter table public.profiles enable row level security;
alter table public.owners enable row level security;
alter table public.pets enable row level security;
alter table public.services enable row level security;
alter table public.appointments enable row level security;
alter table public.appointment_services enable row level security;
alter table public.vaccinations enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists profiles_self_select on public.profiles;
create policy profiles_self_select on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.current_app_role() in ('ADMIN', 'VET', 'RECEPTIONIST'));

drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles
  for update to authenticated
  using (public.current_app_role() = 'ADMIN')
  with check (public.current_app_role() = 'ADMIN');

drop policy if exists owners_read on public.owners;
create policy owners_read on public.owners
  for select to authenticated
  using (auth_user_id = auth.uid() or public.current_app_role() in ('ADMIN', 'VET', 'RECEPTIONIST'));

drop policy if exists owners_staff_write on public.owners;
create policy owners_staff_write on public.owners
  for all to authenticated
  using (public.current_app_role() in ('ADMIN', 'RECEPTIONIST'))
  with check (public.current_app_role() in ('ADMIN', 'RECEPTIONIST'));

drop policy if exists pets_read on public.pets;
create policy pets_read on public.pets
  for select to authenticated
  using (
    exists (select 1 from public.owners o where o.id = owner_id and o.auth_user_id = auth.uid())
    or public.current_app_role() in ('ADMIN', 'VET', 'RECEPTIONIST')
  );

drop policy if exists pets_staff_write on public.pets;
create policy pets_staff_write on public.pets
  for all to authenticated
  using (public.current_app_role() in ('ADMIN', 'RECEPTIONIST'))
  with check (public.current_app_role() in ('ADMIN', 'RECEPTIONIST'));

drop policy if exists services_authenticated_read on public.services;
create policy services_authenticated_read on public.services
  for select to authenticated using (true);

drop policy if exists services_admin_write on public.services;
create policy services_admin_write on public.services
  for all to authenticated
  using (public.current_app_role() = 'ADMIN')
  with check (public.current_app_role() = 'ADMIN');

drop policy if exists appointments_read on public.appointments;
create policy appointments_read on public.appointments
  for select to authenticated
  using (
    exists (
      select 1 from public.pets p
      join public.owners o on o.id = p.owner_id
      where p.id = pet_id and o.auth_user_id = auth.uid()
    )
    or public.current_app_role() in ('ADMIN', 'VET', 'RECEPTIONIST')
  );

drop policy if exists appointments_staff_write on public.appointments;
create policy appointments_staff_write on public.appointments
  for all to authenticated
  using (public.current_app_role() in ('ADMIN', 'VET', 'RECEPTIONIST'))
  with check (public.current_app_role() in ('ADMIN', 'VET', 'RECEPTIONIST'));

drop policy if exists appointment_services_read on public.appointment_services;
create policy appointment_services_read on public.appointment_services
  for select to authenticated using (true);

drop policy if exists appointment_services_staff_write on public.appointment_services;
create policy appointment_services_staff_write on public.appointment_services
  for all to authenticated
  using (public.current_app_role() in ('ADMIN', 'RECEPTIONIST'))
  with check (public.current_app_role() in ('ADMIN', 'RECEPTIONIST'));

drop policy if exists vaccinations_read on public.vaccinations;
create policy vaccinations_read on public.vaccinations
  for select to authenticated
  using (
    exists (
      select 1 from public.pets p
      join public.owners o on o.id = p.owner_id
      where p.id = pet_id and o.auth_user_id = auth.uid()
    )
    or public.current_app_role() in ('ADMIN', 'VET', 'RECEPTIONIST')
  );

drop policy if exists vaccinations_vet_write on public.vaccinations;
create policy vaccinations_vet_write on public.vaccinations
  for all to authenticated
  using (public.current_app_role() in ('ADMIN', 'VET'))
  with check (public.current_app_role() in ('ADMIN', 'VET'));

drop policy if exists audit_logs_staff_read on public.audit_logs;
create policy audit_logs_staff_read on public.audit_logs
  for select to authenticated
  using (public.current_app_role() = 'ADMIN');

drop policy if exists audit_logs_staff_insert on public.audit_logs;
create policy audit_logs_staff_insert on public.audit_logs
  for insert to authenticated
  with check (actor_user_id = auth.uid());

insert into public.services (name, description, price_cents)
values
  ('Consulta general', 'Evaluacion clinica general', 0),
  ('Vacunacion', 'Aplicacion y registro de vacuna', 0),
  ('Control preventivo', 'Revision preventiva y seguimiento', 0)
on conflict (name) do nothing;